augmentations: # write the desired values or null if that augmentation won't be used.
  fliplr: 0.5 # 0.5
  scale: [0.95, 1.05] # [0.95, 1.05]
  brightness: [-10, 10] # [-10, 10]
  saturation: [-10, 10] # [-10, 10] 
  hue: [-10, 10] # [-10, 10]
  add_grayscale: [0, 0.2] # [0, 0.2]
  motion_blur: [3, 5] # [3, 5]
  contrast: [0.8, 1.2] # [0.8, 1.2]
  translate: [[-0.1, 0.1], [-0.1, 0.1]] # [[-0.1, 0.1], [-0.1, 0.1]]
  rotate: [-5, 5] # [-5, 5]
  shear: [-5, 5] # [-5, 5]
